import { useNavigate,useParams } from "react-router-dom";
import { useEffect, useState } from "react";

export default function ServicePageTemplate(){
  const { pageId } = useParams();

  //temporary hard coded content
  //change page id to mach back end data later
    const pageContent = {
    furn: { image:"/Images/service page images/furniture-assembly.webp", title: "Furniture Assembly", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    gutt: { image:"/Images/service page images/Cleaning-Gutters.jpg", title: "Gutter Cleaning", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    homerep: { image:"/Images/service page images/home-repairs.webp", title: "Home Repairs", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    paint: { image:"/Images/service page images/Painting.jpg", title: "Painting", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    plumb: { image:"/Images/service page images/Plumbing.jpeg", title: "Plumbing", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    siding: { image:"/Images/service page images/types-of-vinyl-siding.jpeg", title: "House Siding", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    carp: { image:"/Images/service page images/carpentry.jpg", title: "Carpentry", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    elect: { image:"/Images/service page images/electrical.jpg", title: "Electrical", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    outliv: { image:"/Images/service page images/outdoor living.jpg", title: "Outdoor Living", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    pool: { image:"/Images/service page images/pool.jpg", title: "Pools", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    hards: { image:"/Images/service page images/hardscaping.jpg", title: "Hardscaping", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    patio: { image:"/Images/service page images/patio.jpg", title: "Patios", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
    outkit: { image:"/Images/service page images/outdoor kitchen.jpeg", title: "Outdoor Kitchens", description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque volutpat nibh a hendrerit condimentum. Duis nulla diam, ultrices a viverra pharetra, egestas et magna. Sed elementum rutrum lacus, a commodo felis efficitur ut. Curabitur ornare, mauris vel convallis tempus, turpis augue consectetur sapien, euismod venenatis leo mauris ut dui. Donec vel nisi porttitor, malesuada lectus ut, ornare enim. Vestibulum facilisis interdum purus, id ornare turpis porta vitae. Ut ac interdum quam. Nulla dignissim ullamcorper elit, id ornare augue convallis sit amet. Vivamus molestie, felis placerat dignissim sagittis, massa nulla venenatis velit, quis convallis lacus lacus eget lacus. Proin eu lacus augue. Suspendisse vulputate, ipsum et pulvinar euismod, mi purus pharetra lorem, at gravida leo augue ut arcu. Sed rhoncus, sem sed vestibulum rhoncus, dui metus rutrum est, sit amet gravida ex justo eget mi." },
  };

  const content = pageContent[pageId] || { title: "Not Found", description: "" };
  const navigate = useNavigate();

  const [services, setServices] = useState([]);

  useEffect(() => {
    fetch({/*"http://localhost:5000/api/services" replace with backend url*/}) 
      .then(res => res.json())
      .then(data => setServices(data))
      .catch(err => console.error("Error fetching services:", err));
  }, []);

    return(
        <section className="servpagetemp">
          <div className="spagecontainer">
            <img src={content.image} alt="" />
            <h1>{content.title}
              {/* {service.title} replace with backend title*/}
            </h1>
            <p>{content.description}
              {/* {service.description} replace with backend description */}
            </p>
            <div><button>Pay for Service</button></div>
            <div><button onClick={() => navigate("/") }>Back to Home</button></div>
            <div><button onClick={() => navigate("/services") }>Back to Services</button></div>
            </div>
        </section>
    );
}